routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Home')->name("home");
Route::get('/home', 'Home');
Route::get('/feed', 'AdsController@feed');
Route::view('/entrar', 'users.get-in')->name('getIn');
Route::view('/login', 'users.get-in')->name('login');
Route::post('/cadastrar', 'UsersController@signUp')->name('signUp');
Route::post('/entrar', 'UsersController@signIn')->name('signIn');
Route::get("/perfil/{user}", "UsersController@profile")->where("user", "[0-9]+")->name("users.profile");
Route::get('/anuncio/{ad}/{slug}', 'AdsController@show')->where("ad", "[0-9]+")->name("ads.show");
Route::get('/comprar-bicicleta-{bikeType:slug}', 'AdsController@bicycleType')->name("ads.bike-type");
Route::get('/bike-{slug}', 'AdsController@typeAndBrand')->name("ads.type-brand");
Route::get('/bicicletas-marca-{brand:slug}', 'AdsController@brand')->name("ads.brand");
Route::get('/entre-em-contato', 'ContactFormController@index')->name("contactForm");
Route::post('/entre-em-contato', 'ContactFormController@submit');
Route::get('/mensagem-enviada', 'ContactFormController@success');

Route::get('login/instagram', 'SocialLoginController@redirectToInstagramProvider')->name("login.instagram");
Route::get('login/instagram/callback', 'SocialLoginController@handleInstagramProviderCallback');
Route::get('login/facebook', 'SocialLoginController@redirectToFacebookProvider')->name("login.facebook");
Route::get('login/facebook/callback', 'SocialLoginController@handleFacebookProviderCallback');
Route::get('login/google', 'SocialLoginController@redirectToGoogleProvider')->name("login.google");
Route::get('login/google/callback', 'SocialLoginController@handleGoogleProviderCallback');

Route::namespace("Auth")->group(function () {
    Route::post("/recuperar-senha", "ForgotPasswordController@sendResetLinkEmail")->name("password.email");
    Route::post("/alterar-senha", "ResetPasswordController@reset")->name("password.update");
    Route::get("/recuperar-senha", "ForgotPasswordController@showLinkRequestForm")->name("password.request");
    Route::get("/redefinir-senha/{token}", "ResetPasswordController@showResetForm")->name("password.reset");
});

Route::get('/marcas/buscar/{brand}', 'BrandsController@search')->name("brands.search");
Route::get('/cidade/cep/{zipCode}', 'CitiesController@getCityByZipCode')->name("cities.zipcode");

Route::middleware("auth")->group(function () {
    Route::resource('ads', 'AdsController')->except("show");
    Route::get('/perfil/editar', 'UsersController@editData')->name("users.edit-data");
    Route::put('/perfil/editar', 'UsersController@updateData')->name("users.update-data");
    Route::get('/perfil/editar/contatos', 'UsersController@editContacts')->name("users.edit-contacts");
    Route::put('/perfil/editar/contatos', 'UsersController@updateContacts')->name("users.update-contacts");
    Route::get('/perfil/editar/senha', 'UsersController@editPassword')->name("users.edit-password");
    Route::put('/perfil/editar/senha', 'UsersController@updatePassword')->name("users.update-password");
    Route::get('/sair', 'UsersController@logOut')->name('logout');
});

Route::namespace("Admin")->prefix('admin')->group(function () {
    Route::view("/", "admin.login")->name("admin.index");
    Route::post("/login", "LoginController@login")->name("admin.login");
});

Route::namespace("Admin")->prefix('admin')->name("admin.")->middleware("auth:admin")->group(function () {
    Route::get('/dashboard', 'DashboardController@index')->name("dashboard");
    Route::get('/sitemap', 'DashboardController@generateSitemap')->name("sitemap");
    Route::get('/sair', 'LoginController@logOut')->name('logout');
    Route::resource('ads', 'AdsController');
    Route::post('/ads/import', 'AdsController@import');
    Route::post('/ads/delete-all', 'AdsController@destroyAll');
    Route::resource('brands', 'BrandsController');
    Route::resource('users', 'UsersController');
});

app/Ad.php
<?php

namespace App;

use App\Enums\AdStatusEnum;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Ad extends Model
{
    use SoftDeletes;

    protected $with = ["brand"];

    public function scopePublished($query)
    {
        return $query->where('status', AdStatusEnum::PUBLISHED);
    }

    public function bike()
    {
        return $this->hasOne("App\Bicycle");
    }

    public function comments()
    {
        return $this->hasMany("App\Comment");
    }

    public function brand()
    {
        return $this->belongsTo("App\Brand");
    }

    public function category()
    {
        return $this->belongsTo("App\Category");
    }

    public function photos()
    {
        return $this->hasMany("App\Photo");
    }

    public static function forHomePage()
    {
        return self::whereStatus(1);
    }

    public function user()
    {
        return $this->belongsTo("App\User");
    }

    public function getSlugAttribute()
    {
        $slug = [];
        if ($this->bike) {
            $slug[] = $this->bike->type->name;
        }
        if ($this->brand) {
            $slug[] = $this->brand->slug;
        }
        $slug[] = $this->attributes["description"];
        return Str::slug(implode(" ", $slug));
    }

    public function getWasSoldAttribute()
    {
        return $this->attributes["status"] == AdStatusEnum::SOLD;
    }

    public function getCityAttribute()
    {
        if ($this->user && $this->user->city) {
            return $this->user->city->name . ' - ' . $this->user->city->state_uf;
        }
        return '';
    }

    public function setPriceAttribute($value)
    {
        $this->attributes["price"] = float_from_brl($value);
    }

    public function getStatusAttribute()
    {
        return AdStatusEnum::$name[$this->attributes["status"]];
    }


}

app/Http/Controllers/Admin/AdsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Ad;
use App\BicycleType;
use App\Enums\AdStatusEnum;
use App\Enums\DeletionReasonEnum;
use App\Http\Controllers\Controller;
use App\Http\Requests\Ad\NewAd;
use App\Http\Requests\Ad\EditAd;
use App\Repositories\AdRepository;
use App\User;
use Illuminate\Http\Request;

class AdsController extends Controller
{
    protected $ad;

    public function __construct(AdRepository $ad)
    {
        $this->ad = $ad;
    }

    public function index()
    {
        $ads = Ad::get();
        $deletionReasonSold = DeletionReasonEnum::SOLD;
        return view("admin.ads.index", compact("ads", "deletionReasonSold"));
    }

    public function create()
    {
        $users = User::get()->pluck("name", "id");
        $status = AdStatusEnum::$name;
        $ad = null;
        return view("admin.ads.form", compact("ad", "status", "users"));
    }

    public function import(Request $request)
    {
        $request->validate([
            'url' => 'required|url',
        ]);
        $ad = $this->ad->import($request->url);
        return redirect()->route("admin.ads.edit", ["ad" => $ad->id]);
    }

    public function store(NewAd $request)
    {
        $ad = $this->ad->store($request);
        return redirect()->route("admin.ads.show", ["ad" => $ad->id]);
    }

    public function bicycleType(BicycleType $bikeType)
    {
        $ads = $this->ad->getAdsByBicycleType($bikeType);
        return view("ads.bike-type", compact("ads", "bikeType"));
    }

    public function show(Ad $ad)
    {
        $ad->load("bike", "user");
        $deletionReasons = DeletionReasonEnum::$options;
        return view("admin.ads.show", compact("ad", "deletionReasons"));
    }

    public function edit(Ad $ad)
    {
        $ad->load("brand", "user");
        $status = AdStatusEnum::$name;
        $users = User::get()->pluck("name", "id");
        return view("admin.ads.form", compact("ad", "status", "users"));
    }

    public function update(EditAd $request, Ad $ad)
    {
        $ad = $this->ad->update($request, $ad);
        return redirect()->route("admin.ads.show", ["ad" => $ad->id]);
    }

    public function destroy(Request $request, Ad $ad)
    {
        $this->ad->destroy($request, $ad);
        return redirect()->route("admin.ads.index");
    }

    public function destroyAll(Request $request)
    {
        $this->ad->destroyAll($request);
        return redirect()->route("admin.ads.index")->with("status", "Anúncios excluidos com sucesso!");
    }
}

app/Http/Controllers/AdsController.php
<?php

namespace App\Http\Controllers;

use App\Ad;
use App\BicycleType;
use App\Brand;
use App\Http\Requests\Ad\DeleteAd;
use App\Http\Requests\Ad\NewAd;
use App\Http\Requests\Ad\EditAd;
use App\Repositories\AdRepository;
use Request;
use Storage;
use Illuminate\View\View;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class AdsController extends Controller
{
    protected $ad;

    public function __construct(AdRepository $ad)
    {
        $this->ad = $ad;
    }

    public function index()
    {
        //
    }

    public function create()
    {
        $ad = null;
        return view("ads.form", compact("ad"));
    }

    public function store(NewAd $request)
    {
        $ad = $this->ad->store($request);
        return redirect()
            ->route("ads.show", ["ad" => $ad->id, "slug"=>$ad->slug])
            ->with("status", "Anúncio publicado!");
    }

    public function bicycleType(BicycleType $bikeType)
    {
        $ads = $this->ad->getAdsByBicycleType($bikeType);
        $title = "Bicicletas " . $bikeType->name . "à venda";
        return view("ads.bike-type", compact("ads", "bikeType", "title"));
    }


    public function brand(Brand $brand)
    {
        $ads = $this->ad->getAdsByBrand($brand);
        $brands = Brand::whereHas("ads.bike")->get();
        $title = "Bicicletas ".$brand->name." à venda";
        return view("ads.brand", compact("ads", "brand", "brands", "title"));
    }

    public function typeAndBrand(Request $req, $slug)
    {
        preg_match('/(.+)-(.+)$/', $slug, $matches);
        if (!$matches) {
            dump($slug);
            dd($matches);
            throw new NotFoundHttpException();
        }
        $bikeType = BicycleType::where('slug', $matches[1])->firstOrFail();
        $brand = Brand::where('slug', $matches[2])->firstOrFail();
        $ads = $this->ad->getAdsByTypeAndBrand($bikeType, $brand);
        $bikeByTypeAndBrand = $this->ad->bikeByTypeAndBrand();
        $title = "Bicicletas ".$bikeType->name.' '.$brand->name." à venda";
        return view("ads.type-brand", compact("ads", "bikeByTypeAndBrand", "bikeType", "brand", "title"));
    }

    public function show(Ad $ad)
    {
        $ad->load("bike", "category", "user.city");
        $related = $this->ad->related($ad);
        $breadCrumb = [[
            "name" => "Inicial",
            "item" => route('home')
        ]];
        $view = view("ads.show", compact("ad", "related"));
        if ($ad->bike) {
            $breadCrumb[] = ["name" => $ad->bike->type->name, "item" => route("ads.bike-type", ["bikeType"=>$ad->bike->type->slug])];
            $breadCrumb[] = ["name" => $ad->brand->name, "item" => route("ads.type-brand", ["slug"=>$ad->bike->type->slug."-".$ad->brand->slug])];
            $view->with([
                "keywords" => "bike ".$ad->bike->type->name." ".$ad->brand->name.", bicicleta ".$ad->bike->type->name." ".$ad->brand->name,
                "title" => "Bicicleta " . $ad->bike->type->name . " " . $ad->description
            ]);
        } else {
            $view->with("title", $ad->description);
        }
        $breadCrumb[] = ["name" => $ad->description];
        if ($ad->photos()->count()) {
            $view->with('socialCover', photo($ad->photos()->first()->file));
        }
        $view->with("breadCrumb", $breadCrumb);
        return $view;
    }

    public function edit(Ad $ad)
    {
        $ad->load("brand");
        return view("ads.form", compact("ad"));
    }

    public function update(EditAd $request, Ad $ad)
    {
        $ad = $this->ad->update($request, $ad);
        return redirect()
            ->route("ads.show", ["ad" => $ad->id, "slug"=>$ad->slug])
            ->with("status", "Anúncio atualizado!");
    }

    public function destroy(DeleteAd $request, Ad $ad)
    {
        $this->ad->destroy($request, $ad);
        return redirect()->route("users.profile", auth()->user())
            ->with("status", "Seu anúncio excluído!");
    }

    public function feed()
    {
        $ads = $this->ad->forFeed();
        $contents = "id	title	description	product type	link	image link	condition	availability	price	brand";
        foreach ($ads as $ad) {
            $line = [
                $ad->id,
                $ad->description,
                preg_replace("/\r\n|\r|\n/", ' ', $ad->details),
                $ad->bike ? "Bicicleta > ".$ad->bike->type->name : $ad->category->name,
                route('ads.show', ['ad'=>$ad->id, "slug" => $ad->slug]),
                $ad->photos->count() ? photo_thumb($ad->photos[0]->file) : '',
                'used',
                'in stock',
                $ad->price . " BRL",
                $ad->brand->name
            ];
            $contents .= "\n".implode("\t", $line);
        }
        // dd($contents);
        Storage::disk('local')->put('feed.txt', $contents);
        return response()->file(Storage::path('feed.txt'));
    }
}

resources/views/admin/ads/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="bg-white rounded-lg p-8">
  <div class="flex flex-row justify-between mt-6 mb-6">
    <h2 class="text-2xl font-bold text-gray-500">{{ $ads->count() }} Anúncios</h2>
    <a href="{{ route("admin.ads.create") }}" class="inline-block bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded-lg text-center">Novo Anúncio</a>
    {!! Form::open(["action"=>"Admin\AdsController@import", "class"=>"flex flex-row"]) !!}
    <input type="text" name="url" class="border-2 rounded-lg py-2 px-4">
    <button class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-lg">Importar</button>
    {!! Form::close() !!}
  </div>
  {!! Form::open(["action"=>"Admin\AdsController@destroyAll"]) !!}
  <table class="w-full">
    <thead>
      <tr class="text-left">
        <th class="text-center">#</th>
        <th>Descrição</th>
        <th>Categoria</th>
        <th>Marca</th>
        <th>Valor</th>
        <th>Situação</th>
        <th>Cadastrado em</th>
        <th>Admin</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach ($ads as $ad)
      <tr class="{{ $loop->index % 2 == 0 ? "bg-gray-100" : "bg-white" }} hover:bg-gray-200">
        <td class="text-center">{{ $ad->id }}</td>
        <td>{{ $ad->description }}</td>
        <td>{{ $ad->category->name }}</td>
        <td>{{ $ad->brand ? $ad->brand->name : '' }}</td>
        <td>{{ $ad->price }}</td>
        <td>{{ $ad->status }}</td>
        <td>{{ $ad->created_at }}</td>
        <td>
        @if(empty($ad->source))
        Não
        @else
        <a href="{{$ad->source}}" target="_blank">Sim</a>
        <input type="checkbox" name="ids[]" value="{{$ad->id}}">
        @endif
        </td>
        <td>
          <div class="opacity-0 hover:opacity-100">
            <a href="{{ route("admin.ads.show", ["ad"=>$ad]) }}">ver</a>
            <a href="{{ route("admin.ads.edit", ["ad"=>$ad]) }}">editar</a>
          </div>
        </td>
      </tr>
      @endforeach
    </tbody>
    <tfoot>
      <tr>
        <td colspan="7"></td>
        <td>
          {!!Form::hidden('sold', $deletionReasonSold)!!}
          <button class="border-2 border-red-500 hover:bg-red-500 text-red-500 hover:text-white font-bold py-2 px-4 rounded-lg">x</button>
        </td>
      </tr>
    </tfoot>
  </table>
  {!! Form::close() !!}
</div>
@endsection

resources/views/admin/ads/show.blade.php
@extends('layouts.admin')
@section('content')
<div class="flex flex-col -mt-8 sm:mt-0 md:flex-row">
  <div class="w-full md:w-3/4 md:pr-8">
    <div class="flex flex-row justify-center bg-gray-800">
    @foreach ($ad->photos as $photo)
      <div
        class="w-1/6 bg-cover bg-center bg-no-repeat cursor-pointer transition duration-300 hover:opacity-75"
        style="padding-top:10%; background-image:url('{{photo_thumb($photo->file)}}')"
      >
      </div>
    @endforeach()
    </div>
    <div class="bg-white p-4 pb-0">
      <div>
        <div class="float-right text-right ml-2 mr-1">
          @if ($ad->city)
          <div class="mb-2">
            <i class="icon-location text-gray-600"></i> {{$ad->city}}
          </div>
          @endif
          @if ($ad->receipt)
          <div class="mb-2">
            <div class="receipt">
            <i class="icon-file-alt text-gray-600"></i> Nota fiscal
            </div>
          </div>
          @endif
          @if ($ad->negotiation)
          <div class="receipt">
            <i class="icon-handshake text-gray-600"></i> Aceita negociar
          </div>
          @endif
        </div>
        <h2 class="font-bold text-2xl pb-2 text-green-600">{{ brl_without_zero($ad->price) }}</h2>
        <h2 class="font-bold text-2xl pb-3">{{ $ad->description }}</h2>
      </div>
      <div class="pb-4">{!! nl2br($ad->details, 0) !!}</div>
      <div class="flex flex-col sm:flex-row -mx-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full pl-4 pt-4 sm:py-4 sm:w-1/3 mr-2">Marca</div>
        <div>
          <a
            href="{{ route("ads.brand", ["brand"=>$ad->brand->slug]) }}"
            title="Ver mais bicicletas da marca {{$ad->brand->name}}"
            class="text-blue-500 inline-block py-2 px-4 mb-2 sm:mb-0 sm:mt-2 sm:-ml-2 rounded-full hover:text-white hover:bg-blue-500 transition duration-300"
          >{{$ad->brand->name}}</a>
        </div>
      </div>
      @if($ad->bike)
      @if ($ad->bike->frame_size)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Quadro / Tamanho</div><div>{{$ad->bike->frame_size}}</div>
      </div>
      @endif
      @if ($ad->bike->fork_headset)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Garfo / Headset</div><div>{{$ad->bike->fork_headset}}</div>
      </div>
      @endif
      @if ($ad->bike->handlebars_stem)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Guidão / Mesinha</div><div>{{$ad->bike->handlebars_stem}}</div>
      </div>
      @endif
      @if ($ad->bike->groupset)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Grupo</div><div>{{$ad->bike->groupset}}</div>
      </div>
      @endif
      @if ($ad->bike->brakes)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Freios</div><div>{{$ad->bike->brakes}}</div>
      </div>
      @endif
      @if ($ad->bike->pedals)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Pedais</div><div>{{$ad->bike->pedals}}</div>
      </div>
      @endif
      @if ($ad->bike->saddle_seatpost)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Selim / Canote</div><div>{{$ad->bike->saddle_seatpost}}</div>
      </div>
      @endif
      @if ($ad->bike->front_wheel_hub_tire)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Roda / Cubo / Pneu dianteiro</div><div>{{$ad->bike->front_wheel_hub_tire}}</div>
      </div>
      @endif
      @if ($ad->bike->rear_wheel_hub_tire)
      <div class="flex flex-col sm:flex-row -mx-4 p-4 border-gray-200 border-t">
        <div class="text-gray-700 font-bold w-full sm:w-1/3 mr-2">Roda / Cubo / Pneu traseiro</div><div>{{$ad->bike->rear_wheel_hub_tire}}</div>
      </div>
      @endif
      @endif
    </div>
    <div class="bg-white border-t border-gray-200 p-4">
      <div class="flex flex-col sm:flex-row">
        <a href="{{ route('ads.edit', ['ad' => $ad->id]) }}" class="inline-block bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded-lg text-center">Atualizar</a>
        {!! Form::model($ad, ["route" => ["admin.ads.destroy", $ad], "method" => "delete"]) !!}
        {!! Form::select('sold', $deletionReasons) !!}
        {!! Form::button('<i class="icon-trash mr-2"></i> Excluir', [
          "class" => "cursor-pointer bg-red-400 hover:bg-red-500 text-center text-white font-bold py-2 px-4 w-full sm:w-auto mt-4 sm:mt-0 sm:ml-4 rounded-lg", "type"=>"submit"]) !!}
        {!! Form::close() !!}
      </div>
      <x-user :user="$ad->user" />
    </div>
  </div>
</div>
@endsection