routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Home')->name("home");
Route::get('/home', 'Home');
Route::get('/feed', 'AdsController@feed');
Route::view('/entrar', 'users.get-in')->name('getIn');
Route::view('/login', 'users.get-in')->name('login');
Route::post('/cadastrar', 'UsersController@signUp')->name('signUp');
Route::post('/entrar', 'UsersController@signIn')->name('signIn');
Route::get("/perfil/{user}", "UsersController@profile")->where("user", "[0-9]+")->name("users.profile");
Route::get('/anuncio/{ad}/{slug}', 'AdsController@show')->where("ad", "[0-9]+")->name("ads.show");
Route::get('/comprar-bicicleta-{bikeType:slug}', 'AdsController@bicycleType')->name("ads.bike-type");
Route::get('/bike-{slug}', 'AdsController@typeAndBrand')->name("ads.type-brand");
Route::get('/bicicletas-marca-{brand:slug}', 'AdsController@brand')->name("ads.brand");
Route::get('/entre-em-contato', 'ContactFormController@index')->name("contactForm");
Route::post('/entre-em-contato', 'ContactFormController@submit');
Route::get('/mensagem-enviada', 'ContactFormController@success');

Route::get('login/instagram', 'SocialLoginController@redirectToInstagramProvider')->name("login.instagram");
Route::get('login/instagram/callback', 'SocialLoginController@handleInstagramProviderCallback');
Route::get('login/facebook', 'SocialLoginController@redirectToFacebookProvider')->name("login.facebook");
Route::get('login/facebook/callback', 'SocialLoginController@handleFacebookProviderCallback');
Route::get('login/google', 'SocialLoginController@redirectToGoogleProvider')->name("login.google");
Route::get('login/google/callback', 'SocialLoginController@handleGoogleProviderCallback');

Route::namespace("Auth")->group(function () {
    Route::post("/recuperar-senha", "ForgotPasswordController@sendResetLinkEmail")->name("password.email");
    Route::post("/alterar-senha", "ResetPasswordController@reset")->name("password.update");
    Route::get("/recuperar-senha", "ForgotPasswordController@showLinkRequestForm")->name("password.request");
    Route::get("/redefinir-senha/{token}", "ResetPasswordController@showResetForm")->name("password.reset");
});

Route::get('/marcas/buscar/{brand}', 'BrandsController@search')->name("brands.search");
Route::get('/cidade/cep/{zipCode}', 'CitiesController@getCityByZipCode')->name("cities.zipcode");

Route::middleware("auth")->group(function () {
    Route::resource('ads', 'AdsController')->except("show");
    Route::get('/perfil/editar', 'UsersController@editData')->name("users.edit-data");
    Route::put('/perfil/editar', 'UsersController@updateData')->name("users.update-data");
    Route::get('/perfil/editar/contatos', 'UsersController@editContacts')->name("users.edit-contacts");
    Route::put('/perfil/editar/contatos', 'UsersController@updateContacts')->name("users.update-contacts");
    Route::get('/perfil/editar/senha', 'UsersController@editPassword')->name("users.edit-password");
    Route::put('/perfil/editar/senha', 'UsersController@updatePassword')->name("users.update-password");
    Route::get('/sair', 'UsersController@logOut')->name('logout');
});

Route::namespace("Admin")->prefix('admin')->group(function () {
    Route::view("/", "admin.login")->name("admin.index");
    Route::post("/login", "LoginController@login")->name("admin.login");
});

Route::namespace("Admin")->prefix('admin')->name("admin.")->middleware("auth:admin")->group(function () {
    Route::get('/dashboard', 'DashboardController@index')->name("dashboard");
    Route::get('/sitemap', 'DashboardController@generateSitemap')->name("sitemap");
    Route::get('/sair', 'LoginController@logOut')->name('logout');
    Route::resource('ads', 'AdsController');
    Route::post('/ads/import', 'AdsController@import');
    Route::post('/ads/delete-all', 'AdsController@destroyAll');
    Route::resource('brands', 'BrandsController');
    Route::resource('users', 'UsersController');
});

app/User.php
<?php

namespace App;

use Collective\Html\Eloquent\FormAccessible;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use FormAccessible;
    use CanResetPassword;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', "facebook_id", "google_id", "instagram_id", "avatar"
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getNameAttribute() {
        if ($this->attributes['name']) {
            return $this->attributes['name'];
        }
        return $this->attributes['email'];
    }

    public function formNameAttribute($value)
    {
        return $value;
    }

    public function ads() {
        return $this->hasMany("App\Ad");
    }

    public function city() {
        return $this->belongsTo("App\City");
    }

    public function contacts() {
        return $this->hasMany("App\UserContact");
    }


}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Enums\ContactTypeEnum;
use App\User;
use App\Http\Controllers\Controller;
use App\Services\InstagramBot;
use App\UserContact;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class UsersController extends Controller
{
    public function index()
    {
        $users = User::withCount("ads")->get();
        return view("admin.users.index", compact("users"));
    }

    public function create()
    {
        $user = null;
        return view("admin.users.form", compact("user"));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $user = new User();
        $user->name = $request->name;
        $user->save();

        return redirect()->route("admin.users.index");
    }

    public function edit(User $user)
    {
        $user->load("contacts", "city");
        return view("admin.users.form", compact("user"));
    }

    public function update(Request $request, User $user)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $user->name = $request->name;
        $user->email = $request->email;
        if ($request->zipcode) {
            $user->zipcode = $request->zipcode;
        }
        if ($request->city_id) {
            $user->city_id = $request->city_id;
        }
        foreach ($request->contacts as $contact) {
            if ($contact["id"]) {
                $userContact = UserContact::find($contact["id"]);
                if ($contact["value"] == null) {
                    $userContact->delete();
                    continue;
                }
                $userContact->value = $contact["value"];
                if ($userContact->type == ContactTypeEnum::INSTAGRAM && $request->import_avatar) {
                    $user->avatar = InstagramBot::getProfilePictureFromInstagramByUsername($userContact->value);
                }
                $userContact->save();
                continue;
            }
        }
        $user->save();

        return redirect()->route("admin.users.index");
    }

    public function destroy(Request $request, User $user)
    {
        if ($user->ads()->withTrashed()->count()) {
            throw ValidationException::withMessages([
                "delete"=>"Usuário não pode ser deletado porque possui anúncio vinculado"
            ]);
        }
        $user->delete();
        return redirect()->route("admin.users.index")->with("status", "Usuário deletado");
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\City;
use App\Enums\ContactTypeEnum;
use App\Http\Requests\User\EditUserContacts;
use App\Http\Requests\User\EditUserData;
use App\Http\Requests\User\EditUserPassword;
use App\Http\Requests\User\SignIn;
use App\Http\Requests\User\SignUp;
use App\Repositories\AdRepository;
use App\Repositories\UserRepository;
use App\State;
use App\User;
use Auth;
use Hash;
use Illuminate\Support\Facades\DB;

class UsersController extends Controller
{
    protected $user;

    public function __construct(UserRepository $user)
    {
        $this->user = $user;
    }
    public function signUp(SignUp $request)
    {
        $credentials = $request->only('email', 'password');

        $this->user->store($credentials);

        if (Auth::attempt($credentials)) {
            return redirect()->intended('/');
        }
        return redirect()->to('/');
    }

    public function signIn(SignIn $request)
    {
        $credentials = $request->only('email', 'password');

        if (Auth::attempt($credentials)) {
            $hour = date("G");
            $greetings = "Boa noite";
            if ($hour >= 6 && $hour < 12) {
                $greetings = "Bom dia";
            }
            if ($hour >= 12 && $hour < 18) {
                $greetings = "Boa tarde";
            }
            $phrases = [
                "Que bom te ver por aqui!",
                "Adoramos sua presença!",
                "Fique à vontade!",
            ];
            return redirect()
                ->intended('/')
                ->with(["status"=>$greetings." ".auth()->user()->name."! ".$phrases[rand(0, count($phrases)-1)]]);
        }
        return redirect()
            ->route("signIn")
            ->withInput()
            ->withErrors(["email"=> "E-mail ou senha está incorreto"]);
    }

    public function profile(User $user)
    {
        $adRepository = new AdRepository();
        $ads = $adRepository->getAdsByUser($user->id);
        return view("users.profile", compact("ads", "user"));
    }

    public function editData()
    {
        $user = auth()->user()->load("city");
        return view("users.edit-data", compact("user"));
    }

    public function updateData(EditUserData $request)
    {
        $this->user->updateData($request, auth()->user());
        return redirect()
            ->route("users.edit-data")
            ->with("status", "Dados atualizados!");
    }

    public function editContacts()
    {
        $user = $this->user->getUserForEditContacts(auth()->user());
        return view("users.edit-contacts", compact("user"));
    }

    public function updateContacts(EditUserContacts $request)
    {
        $this->user->updateContacts($request, auth()->user());
        return redirect()
            ->route("users.edit-contacts")
            ->with("status", "Contatos atualizados!");
    }

    public function editPassword()
    {
        $user = auth()->user();
        return view("users.edit-password", compact("user"));
    }

    public function updatePassword(EditUserPassword $request)
    {
        $this->user->updatePassword($request, auth()->user());
        return redirect()
            ->route("users.edit-password")
            ->with("status", "Senha alterada!");
    }

    public function logout()
    {
        $phrases = [
            "Até mais",
            "Venha mais vezes",
            "Retorne quando quiser",
        ];
        $message = $phrases[rand(0, count($phrases)-1)]. " " .auth()->user()->name."!";
        Auth::logout();
        return redirect()->to('/')->with(["status"=>$message]);
    }
}

resources/views/admin/users/form.blade.php
@extends('layouts.admin')
@section('content')
<div class="bg-white rounded-lg p-8">
  @if ($user)
  {!! Form::model($user, ['route' => ['admin.users.update', $user->id], "class"=>"px-4 sm:px-0", 'method' => 'put']) !!}
    <h2 class="font-bold text-2xl text-blue-800 mb-4">Atualizar usuário</h2>
    {!! Form::hidden('id', $user->id) !!}
  @else
  {!! Form::open(['route' => 'admin.users.store', "class"=>"px-4 sm:px-0"]) !!}
    <h2 class="font-bold text-2xl text-blue-800 mb-4">Cadastrar usuário</h2>
  @endif
  <div class="mb-8 flex flex-row">
  @if ($user->avatar)
    <img src="{{ $user->avatar }}.webp" alt="Foto de {{$user->name}}" class="bg-gray-100 rounded-full w-20">
  @else
    <img src="{{ gravatar($user->email) }}" alt="Foto de {{$user->name}}" class="bg-gray-100 rounded-full w-20">
  @endif
  </div>
  <div class="mb-8 flex flex-col sm:flex-row">
    <div class="flex flex-col sm:w-1/2 sm:mr-4">
      {!! Form::label('name', 'Nome') !!}
      {!! Form::text('name', null, ['class' => 'border-2 rounded py-2 px-4']) !!}
      @error('name')
        <div class="text-red-500">{{ $message }}</div>
      @enderror
    </div>
    <div class="flex flex-col sm:w-1/2 sm:ml-4">
      {!! Form::label('email', 'E-mail') !!}
      {!! Form::text('email', null, ['class' => 'border-2 rounded py-2 px-4']) !!}
      @error('email')
        <div class="text-red-500">{{ $message }}</div>
      @enderror
    </div>
  </div>
  <x-user-zipcode-city :user="$user" />
  @foreach ($user->contacts as $contact)
  <div class="flex flex-col mb-8">
    {!! Form::label("contacts[".$contact->type."][value]", $contact->name) !!}
    {!! Form::text("contacts[".$contact->type."][value]", null, ["class" => "border-2 rounded py-2 px-4"]) !!}
    {!! Form::hidden("contacts[".$contact->type."][type]", null) !!}
    {!! Form::hidden("contacts[".$contact->type."][id]", null) !!}
    @if ($contact->type == 0)
    <label>{!! Form::checkbox('import_avatar', "1") !!} Importar avatar usando bot do Instagram</label>
    @endif
    @error("user.contacts[".$contact->type."].value")
      <div class="alert alert-danger">{{ $message }}</div>
    @enderror
  </div>
  @endforeach
  <div>
    <button class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-lg">Salvar</button>
    <a
      href="{{ route("admin.users.index")}}"
      class="hover:underline text-gray-800 font-bold py-2 px-4 text-center"
    >Cancelar</a>
  </div>
{!! Form::close() !!}
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="bg-white rounded-lg p-8">
  <a href="{{ route("admin.users.create") }}" class="inline-block bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded-lg text-center">Cadastrar usuário</a>
  <h2 class="mt-6 text-2xl font-bold text-gray-500 mb-6">{{ $users->count() }} Usuários</h2>
  <table class="w-full bg-white">
    <thead>
      <tr class="text-left">
        <th class="text-center">#</th>
        <th colspan="2">Nome</th>
        <th>Anúncios</th>
        <th>Cadastrado em</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach ($users as $user)
      <tr class="bg-{{ $loop->index % 2 == 0 ? "white" : "gray-200" }}">
        <td class="text-center">{{ $user->id }}</td>
        <td>
          @if ($user->avatar)
            <span
            class="inline-block w-8 h-8 bg-no-repeat bg-center bg-contain"
            style="background-image:url('{{ $user->avatar }}.webp')"
            ></span>
          @else
            <span
            class="inline-block w-8 h-8 bg-no-repeat bg-center bg-contain"
            style="background-image:url('{{ gravatar($user->email) }}')"
            ></span>
          @endif
        </td>
        <td>{{ $user->name }}</td>
        <td>{{ $user->ads_count }}</td>
        <td>{{ $user->created_at }}</td>
        <td>
          <div class="opacity-0 hover:opacity-100 flex flex row">
            <a href="{{ route("admin.users.edit", ["user"=>$user]) }}">editar</a>
            {!! Form::model($user, ["route"=>["admin.users.destroy", "user"=>$user], "method"=>"delete"]) !!}
            <input type="submit" value="deletar" class="bg-transparent ml-2">
            {!! Form::close() !!}
          </div>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@endsection