routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', 'Home')->name("home");
Route::get('/home', 'Home');
Route::get('/feed', 'AdsController@feed');
Route::view('/entrar', 'users.get-in')->name('getIn');
Route::view('/login', 'users.get-in')->name('login');
Route::post('/cadastrar', 'UsersController@signUp')->name('signUp');
Route::post('/entrar', 'UsersController@signIn')->name('signIn');
Route::get("/perfil/{user}", "UsersController@profile")->where("user", "[0-9]+")->name("users.profile");
Route::get('/anuncio/{ad}/{slug}', 'AdsController@show')->where("ad", "[0-9]+")->name("ads.show");
Route::get('/comprar-bicicleta-{bikeType:slug}', 'AdsController@bicycleType')->name("ads.bike-type");
Route::get('/bike-{slug}', 'AdsController@typeAndBrand')->name("ads.type-brand");
Route::get('/bicicletas-marca-{brand:slug}', 'AdsController@brand')->name("ads.brand");
Route::get('/entre-em-contato', 'ContactFormController@index')->name("contactForm");
Route::post('/entre-em-contato', 'ContactFormController@submit');
Route::get('/mensagem-enviada', 'ContactFormController@success');

Route::get('login/instagram', 'SocialLoginController@redirectToInstagramProvider')->name("login.instagram");
Route::get('login/instagram/callback', 'SocialLoginController@handleInstagramProviderCallback');
Route::get('login/facebook', 'SocialLoginController@redirectToFacebookProvider')->name("login.facebook");
Route::get('login/facebook/callback', 'SocialLoginController@handleFacebookProviderCallback');
Route::get('login/google', 'SocialLoginController@redirectToGoogleProvider')->name("login.google");
Route::get('login/google/callback', 'SocialLoginController@handleGoogleProviderCallback');

Route::namespace("Auth")->group(function () {
    Route::post("/recuperar-senha", "ForgotPasswordController@sendResetLinkEmail")->name("password.email");
    Route::post("/alterar-senha", "ResetPasswordController@reset")->name("password.update");
    Route::get("/recuperar-senha", "ForgotPasswordController@showLinkRequestForm")->name("password.request");
    Route::get("/redefinir-senha/{token}", "ResetPasswordController@showResetForm")->name("password.reset");
});

Route::get('/marcas/buscar/{brand}', 'BrandsController@search')->name("brands.search");
Route::get('/cidade/cep/{zipCode}', 'CitiesController@getCityByZipCode')->name("cities.zipcode");

Route::middleware("auth")->group(function () {
    Route::resource('ads', 'AdsController')->except("show");
    Route::get('/perfil/editar', 'UsersController@editData')->name("users.edit-data");
    Route::put('/perfil/editar', 'UsersController@updateData')->name("users.update-data");
    Route::get('/perfil/editar/contatos', 'UsersController@editContacts')->name("users.edit-contacts");
    Route::put('/perfil/editar/contatos', 'UsersController@updateContacts')->name("users.update-contacts");
    Route::get('/perfil/editar/senha', 'UsersController@editPassword')->name("users.edit-password");
    Route::put('/perfil/editar/senha', 'UsersController@updatePassword')->name("users.update-password");
    Route::get('/sair', 'UsersController@logOut')->name('logout');
});

Route::namespace("Admin")->prefix('admin')->group(function () {
    Route::view("/", "admin.login")->name("admin.index");
    Route::post("/login", "LoginController@login")->name("admin.login");
});

Route::namespace("Admin")->prefix('admin')->name("admin.")->middleware("auth:admin")->group(function () {
    Route::get('/dashboard', 'DashboardController@index')->name("dashboard");
    Route::get('/sitemap', 'DashboardController@generateSitemap')->name("sitemap");
    Route::get('/sair', 'LoginController@logOut')->name('logout');
    Route::resource('ads', 'AdsController');
    Route::post('/ads/import', 'AdsController@import');
    Route::post('/ads/delete-all', 'AdsController@destroyAll');
    Route::resource('brands', 'BrandsController');
    Route::resource('users', 'UsersController');
});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    public function ads()
    {
        return $this->hasMany("App\Ad");
    }
}

app/Http/Controllers/Admin/BrandsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Brand;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class BrandsController extends Controller
{
    public function index()
    {
        $brands = Brand::withCount("ads")->get();
        return view("admin.brands.index", compact("brands"));
    }

    public function create()
    {
        $brand = null;
        return view("admin.brands.form", compact("brand"));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $brand = new Brand();
        $brand->name = $request->name;
        $brand->slug = Str::slug($brand->name);
        $brand->save();

        return redirect()->route("admin.brands.index");
    }

    public function edit(Brand $brand)
    {
        return view("admin.brands.form", compact("brand"));
    }

    public function update(Request $request, Brand $brand)
    {
        $request->validate([
            'name' => 'required',
        ]);
        $brand->name = $request->name;
        $brand->slug = Str::slug($brand->name);
        $brand->save();
        return redirect()->route("admin.brands.index");
    }

    public function destroy(Request $request, Brand $brand)
    {
        if ($brand->ads()->withTrashed()->count()) {
            throw ValidationException::withMessages([
                "delete"=>"Marca não pode ser deletada porque possui anúncio vinculado"
            ]);
        }
        $brand->delete();
        return redirect()->route("admin.brands.index")->with("status", "Marca deletada");
    }
}

app/Http/Controllers/BrandsController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use Illuminate\Http\Request;

class BrandsController extends Controller
{
    public function search(Request $request, $brand)
    {
        $brands = Brand::select("id", "name")->where('name', 'like', "%".$brand."%")->get();
        return response()->json($brands);
    }
}

resources/views/admin/brands/form.blade.php
@extends('layouts.admin')
@section('content')
<div class="bg-white rounded-lg p-8">
  @if ($brand)
  {!! Form::model($brand, ['route' => ['admin.brands.update', $brand->id], "class"=>"px-4 sm:px-0", 'method' => 'put']) !!}
    <h2 class="font-bold text-2xl text-blue-800 mb-4">Atualizar marca</h2>
    {!! Form::hidden('id', $brand->id) !!}
  @else
  {!! Form::open(['route' => 'admin.brands.store', "class"=>"px-4 sm:px-0"]) !!}
    <h2 class="font-bold text-2xl text-blue-800 mb-4">Cadastrar marca</h2>
  @endif
  <div class="mb-8 flex flex-col sm:w-1/2">
    {!! Form::label('name', 'Nome') !!}
    {!! Form::text('name', null, ['class' => 'border-2 rounded py-2 px-4']) !!}
    @error('name')
      <div class="text-red-500">{{ $message }}</div>
    @enderror
  </div>
  <div>
    <button class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded-lg">Salvar</button>
    <a
      href="{{ route("admin.brands.index")}}"
      class="hover:underline text-gray-800 font-bold py-2 px-4 text-center"
    >Cancelar</a>
  </div>
{!! Form::close() !!}
</div>
@endsection

resources/views/admin/brands/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="bg-white rounded-lg p-8">
  <a href="{{ route("admin.brands.create") }}" class="inline-block bg-blue-400 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded-lg text-center">Cadastrar marca</a>
  <h2 class="mt-6 text-2xl font-bold text-gray-500 mb-6">{{ $brands->count() }} Marcas</h2>
  <table class="w-full bg-white">
    <thead>
      <tr class="text-left">
        <th class="text-center">#</th>
        <th>Marca</th>
        <th>Anúncios</th>
        <th>Cadastrado em</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      @foreach ($brands as $brand)
      <tr class="bg-{{ $loop->index % 2 == 0 ? "white" : "gray-200" }}">
        <td class="text-center">{{ $brand->id }}</td>
        <td>
          <span
          class="inline-block w-4 h-4 ml-2 bg-no-repeat bg-center bg-contain"
          style="background-image:url('{{ asset("img/brands/".$brand->slug.".png") }}')"
          ></span>
          {{ $brand->name }}
        </td>
        <td>{{ $brand->ads_count }}</td>
        <td>{{ $brand->created_at }}</td>
        <td>
          <div class="opacity-0 hover:opacity-100 flex flex row">
            <a href="{{ route("admin.brands.edit", ["brand"=>$brand]) }}">editar</a>
            {!! Form::model($brand, ["route"=>["admin.brands.destroy", "brand"=>$brand], "method"=>"delete"]) !!}
            <input type="submit" value="deletar" class="bg-transparent ml-2">
            {!! Form::close() !!}
          </div>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@endsection